import sys

def replace_in_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    replacements = [
        (
            "const STATE = { TITLE: 'title', PLAYING: 'playing', GAMEOVER: 'gameover', WIN: 'win', SHOP: 'shop', ACHIEVEMENTS: 'achievements', COSMETICS: 'cosmetics' };\n            let state = STATE.TITLE;\n\n            let gameData = { coins: 0, upgrades: { lives: 0, shield: 0, cooldown: 0, speed: 0, power: 0 }, bestScore: 0, stats: { totalSlaps: 0, perfectSlaps: 0, gamesPlayed: 0, totalCoinsEarned: 0 }, achievements: {}, cosmetics: ['none'], currentHat: 'none' };",
            "const STATE = { TITLE: 'title', PLAYING: 'playing', GAMEOVER: 'gameover', WIN: 'win', SHOP: 'shop', ACHIEVEMENTS: 'achievements', COSMETICS: 'cosmetics', PRESTIGE: 'prestige' };\n            let state = STATE.TITLE;\n\n            let gameData = { coins: 0, upgrades: { lives: 0, shield: 0, cooldown: 0, speed: 0, power: 0 }, bestScore: 0, stats: { totalSlaps: 0, perfectSlaps: 0, gamesPlayed: 0, totalCoinsEarned: 0 }, achievements: {}, cosmetics: ['none'], currentHat: 'none', prestige: 0 };"
        ),
        (
            "if (!gameData.stats.wins) gameData.stats.wins = 1;\n                if (!gameData.achievements) gameData.achievements = {};\n                if (!gameData.cosmetics) gameData.cosmetics = ['none'];",
            "if (!gameData.stats.wins) gameData.stats.wins = 1;\n                if (!gameData.achievements) gameData.achievements = {};\n                if (!gameData.cosmetics) gameData.cosmetics = ['none'];\n                if (gameData.prestige === undefined) gameData.prestige = 0;"
        ),
        (
            "                // Cosmetics Button\n                ctx.fillStyle = '#e91e63';\n                roundRect(ctx, 110, 560, canvas.width - 220, 46, 12);\n                ctx.fill();\n                ctx.fillStyle = '#fff';\n                ctx.font = '18px sans-serif';\n                ctx.fillText('Cosmetics / Cosm.', canvas.width / 2, 590);\n\n                ctx.restore();",
            "                // Cosmetics Button\n                ctx.fillStyle = '#e91e63';\n                roundRect(ctx, 110, 560, canvas.width - 220, 46, 12);\n                ctx.fill();\n                ctx.fillStyle = '#fff';\n                ctx.font = '18px sans-serif';\n                ctx.fillText('Cosmetics / Cosm.', canvas.width / 2, 590);\n\n                if (gameData.stats.wins >= 10) {\n                    // Prestige Button\n                    ctx.fillStyle = '#ffd700';\n                    roundRect(ctx, 110, 620, canvas.width - 220, 46, 12);\n                    ctx.fill();\n                    ctx.fillStyle = '#000';\n                    ctx.font = '18px sans-serif';\n                    ctx.fillText('Prestige / Prestigio', canvas.width / 2, 650);\n                }\n\n                ctx.restore();"
        ),
        (
            "                    // Check Cosmetics Button (110, 560, w, 46)\n                    else if (pos.y >= 560 && pos.y <= 606 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.COSMETICS;\n                    }\n                } else if (state === STATE.SHOP) {",
            "                    // Check Cosmetics Button (110, 560, w, 46)\n                    else if (pos.y >= 560 && pos.y <= 606 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.COSMETICS;\n                    }\n                    // Check Prestige Button\n                    else if (gameData.stats.wins >= 10 && pos.y >= 620 && pos.y <= 666 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.PRESTIGE;\n                    }\n                } else if (state === STATE.SHOP) {"
        ),
        (
            "                    else if (pos.y >= 560 && pos.y <= 606 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.COSMETICS;\n                    }\n                    return;\n                }\n                if (state === STATE.GAMEOVER",
            "                    else if (pos.y >= 560 && pos.y <= 606 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.COSMETICS;\n                    }\n                    else if (gameData.stats.wins >= 10 && pos.y >= 620 && pos.y <= 666 && pos.x >= 110 && pos.x <= canvas.width - 110) {\n                        setDirectionsVisible(false);\n                        state = STATE.PRESTIGE;\n                    }\n                    return;\n                }\n                if (state === STATE.GAMEOVER"
        ),
        (
            "                else if (state === STATE.ACHIEVEMENTS) drawAchievements();\n                else if (state === STATE.COSMETICS) drawCosmetics();\n                else if (state === STATE.WIN) {",
            "                else if (state === STATE.ACHIEVEMENTS) drawAchievements();\n                else if (state === STATE.COSMETICS) drawCosmetics();\n                else if (state === STATE.PRESTIGE) drawPrestige();\n                else if (state === STATE.WIN) {"
        ),
        (
            "                ctx.fillText('Back / Volver', canvas.width / 2, canvas.height - 40);\n                ctx.restore();\n            }",
            "                ctx.fillText('Back / Volver', canvas.width / 2, canvas.height - 40);\n                ctx.restore();\n            }\n\n            function drawPrestige() {\n                drawBackground();\n                ctx.save();\n                ctx.fillStyle = 'rgba(0,0,0,0.85)';\n                roundRect(ctx, 20, 20, canvas.width - 40, canvas.height - 40, 16);\n                ctx.fill();\n\n                ctx.fillStyle = '#ffd700';\n                ctx.textAlign = 'center';\n                ctx.font = 'bold 30px sans-serif';\n                ctx.fillText('PRESTIGE', canvas.width / 2, 70);\n\n                ctx.fillStyle = '#fff';\n                ctx.font = '16px sans-serif';\n                ctx.fillText('Current Prestige: ' + (gameData.prestige || 0), canvas.width / 2, 120);\n                ctx.fillText('Current Multiplier: x' + (1 + (gameData.prestige || 0) * 0.5).toFixed(1), canvas.width / 2, 150);\n\n                ctx.fillStyle = '#aaa';\n                ctx.font = '14px sans-serif';\n                ctx.fillText('Prestiging will reset:', canvas.width / 2, 220);\n                ctx.fillStyle = '#ff5555';\n                ctx.fillText('- Coins', canvas.width / 2, 250);\n                ctx.fillText('- Upgrades', canvas.width / 2, 280);\n                ctx.fillText('- Levels/Wins', canvas.width / 2, 310);\n                \n                ctx.fillStyle = '#55ff55';\n                ctx.fillText('But you gain:', canvas.width / 2, 360);\n                ctx.fillText('+0.5x Permanent Multiplier!', canvas.width / 2, 390);\n\n                // Prestige Button\n                ctx.fillStyle = '#ff9f1c';\n                roundRect(ctx, 60, canvas.height - 150, canvas.width - 120, 50, 10);\n                ctx.fill();\n                ctx.fillStyle = '#fff';\n                ctx.font = '20px sans-serif';\n                ctx.fillText('PRESTIGE NOW!', canvas.width / 2, canvas.height - 117);\n\n                // Back Button\n                ctx.fillStyle = '#ff5252';\n                roundRect(ctx, 100, canvas.height - 70, canvas.width - 200, 50, 10);\n                ctx.fill();\n                ctx.fillStyle = '#fff';\n                ctx.font = '18px sans-serif';\n                ctx.fillText('Back / Volver', canvas.width / 2, canvas.height - 40);\n\n                ctx.restore();\n            }"
        ),
        (
            "                if (state === STATE.COSMETICS) {\n                    let y = 140;",
            "                if (state === STATE.PRESTIGE) {\n                    if (pos.y >= canvas.height - 150 && pos.y <= canvas.height - 100 && pos.x >= 60 && pos.x <= canvas.width - 60) {\n                        gameData.coins = 0;\n                        gameData.upgrades = { lives: 0, shield: 0, cooldown: 0, speed: 0, power: 0 };\n                        gameData.stats.wins = 1;\n                        gameData.prestige = (gameData.prestige || 0) + 1;\n                        saveGameData();\n                        playSound(1200, 0.2);\n                        setDirectionsVisible(true);\n                        state = STATE.TITLE;\n                    }\n                    if (pos.y >= canvas.height - 70 && pos.y <= canvas.height - 24 && pos.x >= 100 && pos.x <= canvas.width - 100) {\n                        setDirectionsVisible(true);\n                        state = STATE.TITLE;\n                    }\n                    return;\n                }\n\n                if (state === STATE.COSMETICS) {\n                    let y = 140;"
        ),
        (
            "                        c.slapped = true;\n                        c.isPerfect = isPerfect;\n                        c.rotSpeed = (Math.random() < 0.5 ? -1 : 1) * (isPerfect ? 35 : 15 + Math.random() * 10);\n                        slappedAny = true;\n                        comboCount++;\n                        score += comboCount;",
            "                        c.slapped = true;\n                        c.isPerfect = isPerfect;\n                        c.rotSpeed = (Math.random() < 0.5 ? -1 : 1) * (isPerfect ? 35 : 15 + Math.random() * 10);\n                        slappedAny = true;\n                        comboCount++;\n                        const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                        score += comboCount * pMult;"
        ),
        (
            "                        if (c.rallyCount > 0) {\n                            score += 20 * c.rallyCount;\n                            gameData.coins += 5 * c.rallyCount;\n                            gameData.stats.totalCoinsEarned += 5 * c.rallyCount;\n                            addFloatText('MEGA HIT! 💥', c.x, c.y - 30);",
            "                        if (c.rallyCount > 0) {\n                            const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                            score += 20 * c.rallyCount * pMult;\n                            gameData.coins += 5 * c.rallyCount * pMult;\n                            gameData.stats.totalCoinsEarned += 5 * c.rallyCount * pMult;\n                            addFloatText('MEGA HIT! 💥', c.x, c.y - 30);"
        ),
        (
            "                        // Add float text\n                        if (isPerfect) {\n                            gameData.coins += 2;\n                            gameData.stats.totalCoinsEarned += 2;\n                            addFloatText('PERFECT! +2💰' + comboText, c.x, c.y - 10);\n                            spawnImpact(c.x, c.y, true);\n                            playSound(850, 0.15);\n                            triggerShake(6, 0.2);\n                            triggerFlash(0.15, '#fff');\n                            hitStop = 0.15;\n                            spawnRoseExplosion(c.x, c.y);\n                        } else if (c.type === 'golden') {\n                            gameData.coins += 50;\n                            gameData.stats.totalCoinsEarned += 50;\n                            addFloatText('GOLDEN! +50💰' + comboText, c.x, c.y - 10, '#ffd700');\n                            spawnImpact(c.x, c.y, true);\n                            playSound(1200, 0.2);\n                            triggerShake(8, 0.25);\n                            triggerFlash(0.2, '#ffd700');\n                            hitStop = 0.2;\n                            spawnRoseExplosion(c.x, c.y);\n                        } else {\n                            gameData.coins += 1;\n                            gameData.stats.totalCoinsEarned += 1;\n                            addFloatText('SLAP! +1💰' + comboText, c.x, c.y);\n                            spawnImpact(c.x, c.y);\n                            playSound(600, 0.1);\n                        }",
            "                        // Add float text\n                        const pMultCoin = 1 + (gameData.prestige || 0) * 0.5;\n                        if (isPerfect) {\n                            gameData.coins += 2 * pMultCoin;\n                            gameData.stats.totalCoinsEarned += 2 * pMultCoin;\n                            addFloatText(`PERFECT! +${2 * pMultCoin}💰` + comboText, c.x, c.y - 10);\n                            spawnImpact(c.x, c.y, true);\n                            playSound(850, 0.15);\n                            triggerShake(6, 0.2);\n                            triggerFlash(0.15, '#fff');\n                            hitStop = 0.15;\n                            spawnRoseExplosion(c.x, c.y);\n                        } else if (c.type === 'golden') {\n                            gameData.coins += 50 * pMultCoin;\n                            gameData.stats.totalCoinsEarned += 50 * pMultCoin;\n                            addFloatText(`GOLDEN! +${50 * pMultCoin}💰` + comboText, c.x, c.y - 10, '#ffd700');\n                            spawnImpact(c.x, c.y, true);\n                            playSound(1200, 0.2);\n                            triggerShake(8, 0.25);\n                            triggerFlash(0.2, '#ffd700');\n                            hitStop = 0.2;\n                            spawnRoseExplosion(c.x, c.y);\n                        } else {\n                            gameData.coins += 1 * pMultCoin;\n                            gameData.stats.totalCoinsEarned += 1 * pMultCoin;\n                            addFloatText(`SLAP! +${1 * pMultCoin}💰` + comboText, c.x, c.y);\n                            spawnImpact(c.x, c.y);\n                            playSound(600, 0.1);\n                        }"
        ),
        (
            "                                    const comboPhrase = getComboPhrase(comboCount);\n                                    addFloatText(`CHAIN! x${comboCount} ${comboPhrase}`, other.x, other.y);\n                                    spawnImpact(other.x, other.y);\n                                    spawnChainEffect(c.x, c.y, other.x, other.y);\n                                    playSound(700, 0.1);\n                                    score += 5 + comboCount; // Bonus score for chaotic skill",
            "                                    const comboPhrase = getComboPhrase(comboCount);\n                                    addFloatText(`CHAIN! x${comboCount} ${comboPhrase}`, other.x, other.y);\n                                    spawnImpact(other.x, other.y);\n                                    spawnChainEffect(c.x, c.y, other.x, other.y);\n                                    playSound(700, 0.1);\n                                    const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                                    score += (5 + comboCount) * pMult; // Bonus score for chaotic skill"
        ),
        (
            "                    if (!c.slapped && c.type !== 'meteor' && rectsOverlap(player, c)) {\n                        if (c.isShrapnel && c.vy < 0) continue; // Don't hurt player if flying upwards\n                        if (dashTimer > 0) { // I-frames during dash -> Perfect Dodge (Graze)\n                            if (!c.grazed) {\n                                c.grazed = true;\n                                score += 5;",
            "                    if (!c.slapped && c.type !== 'meteor' && rectsOverlap(player, c)) {\n                        if (c.isShrapnel && c.vy < 0) continue; // Don't hurt player if flying upwards\n                        if (dashTimer > 0) { // I-frames during dash -> Perfect Dodge (Graze)\n                            if (!c.grazed) {\n                                c.grazed = true;\n                                const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                                score += 5 * pMult;"
        ),
        (
            "                        } else {\n                            score += 1;\n                            const prevBest = bestScore;",
            "                        } else {\n                            const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                            score += 1 * pMult;\n                            const prevBest = bestScore;"
        ),
        (
            "            function triggerWin() {\n                const defeatedLevel = gameData.stats.wins || 1;\n                const bonus = 50 + (defeatedLevel - 1) * 50;\n                gameData.coins += bonus;\n                gameData.stats.totalCoinsEarned += bonus;",
            "            function triggerWin() {\n                const defeatedLevel = gameData.stats.wins || 1;\n                const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                const bonus = (50 + (defeatedLevel - 1) * 50) * pMult;\n                gameData.coins += bonus;\n                gameData.stats.totalCoinsEarned += bonus;"
        ),
        (
            "                if (fiestaMode) {\n                    fiestaHue = (fiestaHue + dt * 200) % 360;\n                    score += dt * 50; // passive score",
            "                if (fiestaMode) {\n                    fiestaHue = (fiestaHue + dt * 200) % 360;\n                    const pMult = 1 + (gameData.prestige || 0) * 0.5;\n                    score += dt * 50 * pMult; // passive score"
        )
    ]

    # Try replacements
    for i, (search, replace) in enumerate(replacements):
        if search not in content:
            print(f"Warning: Match {i} not found in {filepath}!")
        else:
            content = content.replace(search, replace, 1)

    with open(filepath, 'w') as f:
        f.write(content)

    print(f"Successfully processed {filepath}")

replace_in_file('index.html')
replace_in_file('chancla_bomb.html')
